"""
Core encryption functions
"""

import base64


def encrypt_to_lua(text, key="default_key"):
    """
    Mengenkripsi teks ke dalam format Lua dengan XOR sederhana
    
    Args:
        text (str): Teks yang akan dienkripsi
        key (str): Kunci enkripsi
    
    Returns:
        str: Kode Lua yang terenkripsi
    """
    if not text:
        raise ValueError("Text cannot be empty")
    
    if not key:
        raise ValueError("Key cannot be empty")
    
    # Enkripsi XOR
    encrypted_bytes = []
    for i, char in enumerate(text):
        key_char = key[i % len(key)]
        encrypted_byte = ord(char) ^ ord(key_char)
        encrypted_bytes.append(encrypted_byte)
    
    # Generate Lua code
    lua_code = f"""-- Lua Encrypted Code
-- Generated by Lua Encryptor v1.0.0
-- https://github.com/username/lua-encryptor

local function decrypt(data, key)
    local result = ""
    for i = 1, #data do
        local key_char = key:sub((i-1) % #key + 1, (i-1) % #key + 1)
        result = result .. string.char(bit32.bxor(data:byte(i), key:byte((i-1) % #key + 1)))
    end
    return result
end

local encrypted_data = "{''.join(f'\\\\{byte:03d}' for byte in encrypted_bytes)}"
local key = "{key}"

-- Decrypt and execute
local decrypted = decrypt(encrypted_data, key)
print(decrypted)
-- loadstring(decrypted)()  -- Uncomment to execute
"""
    return lua_code


def encrypt_to_lua_base64(text, key="default_key"):
    """
    Mengenkripsi teks ke dalam format Lua dengan Base64
    
    Args:
        text (str): Teks yang akan dienkripsi
        key (str): Kunci enkripsi
    
    Returns:
        str: Kode Lua yang terenkripsi (Base64)
    """
    if not text:
        raise ValueError("Text cannot be empty")
    
    if not key:
        raise ValueError("Key cannot be empty")
    
    # Enkripsi XOR
    encrypted_bytes = []
    for i, char in enumerate(text):
        key_char = key[i % len(key)]
        encrypted_byte = ord(char) ^ ord(key_char)
        encrypted_bytes.append(encrypted_byte)
    
    # Convert to base64
    encrypted_data = bytes(encrypted_bytes)
    b64_data = base64.b64encode(encrypted_data).decode('utf-8')
    
    # Generate Lua code with Base64
    lua_code = f"""-- Lua Encrypted Code (Base64)
-- Generated by Lua Encryptor v1.0.0
-- https://github.com/username/lua-encryptor

local function decrypt_base64(data, key)
    -- Simple Base64 decoder
    local function b64_decode(str)
        local b64chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
        local result = ""
        for i = 1, #str, 4 do
            local a, b, c, d = str:byte(i, i+3)
            if not a then break end
            a = b64chars:find(string.char(a), 1, true) - 1
            b = b and b64chars:find(string.char(b), 1, true) - 1 or 0
            c = c and b64chars:find(string.char(c), 1, true) - 1 or 0
            d = d and b64chars:find(string.char(d), 1, true) - 1 or 0
            result = result .. string.char(
                (a << 2) | (b >> 4),
                (b << 4) | (c >> 2),
                (c << 6) | d
            )
        end
        return result
    end
    
    local decoded = b64_decode(data)
    local result = ""
    for i = 1, #decoded do
        local key_char = key:sub((i-1) % #key + 1, (i-1) % #key + 1)
        result = result .. string.char(decoded:byte(i) ~ key:byte((i-1) % #key + 1))
    end
    return result
end

local encrypted_data = "{b64_data}"
local key = "{key}"

local decrypted = decrypt_base64(encrypted_data, key)
print(decrypted)
"""
    return lua_code
